- hosts: ansible
#   become: true

  # create docker images
  tasks:
  - name: create a config server image with deployed jar file
    command: docker build . -f Dockerfile_config -t isakggong/config-server:maryfarm-1.0
    tags: create_image
  - name: create a discovery server docker image with deployed jar file
    command: docker build . -f Dockerfile_discovery -t isakggong/discovery-server:maryfarm-1.0
    tags: create_image
  - name: create a apigateway server docker image with deployed jar file
    command: docker build . -f Dockerfile_apigateway -t isakggong/apigateway-server:maryfarm-1.0
    tags: create_image
  - name: create a notify server docker image with deployed jar file
    command: docker build . -f Dockerfile_notify -t isakggong/notify-server:maryfarm-1.0
    tags: create_image
  - name: create a user server docker image with deployed jar file
    command: docker build . -f Dockerfile_user -t isakggong/user-server:maryfarm-1.0
    tags: create_image
  - name: create a plant server docker image with deployed jar file
    command: docker build . -f Dockerfile_plant -t isakggong/plant-server:maryfarm-1.0
    tags: create_image
  - name: create a chat server docker image with deployed jar file
    command: docker build . -f Dockerfile_chat -t isakggong/chat-server:maryfarm-1.0
    tags: create_image
  - name: create a board server docker image with deployed jar file
    command: docker build . -f Dockerfile_board -t isakggong/board-server:maryfarm-1.0
    tags: create_image
  - name: create a calendar server docker image with deployed jar file
    command: docker build . -f Dockerfile_calendar -t isakggong/calendar-server:maryfarm-1.0
    tags: create_image

  # push the images to Docker hub
  - name: push the config image on Docker Hub
    command: docker push isakggong/config-server:maryfarm-1.0
    tags: push_image
  - name: push the discovery image on Docker Hub
    command: docker push isakggong/discovery-server:maryfarm-1.0
    tags: push_image
  - name: push the apigateway image on Docker Hub
    command: docker push isakggong/apigateway-server:maryfarm-1.0
    tags: push_image
  - name: push the notify image on Docker Hub
    command: docker push isakggong/notify-server:maryfarm-1.0   
    tags: push_image
  - name: push the user image on Docker Hub
    command: docker push isakggong/user-server:maryfarm-1.0
    tags: push_image
  - name: push the plant image on Docker Hub
    command: docker push isakggong/plant-server:maryfarm-1.0
    tags: push_image
  - name: push the chat image on Docker Hub
    command: docker push isakggong/chat-server:maryfarm-1.0
    tags: push_image
  - name: push the board image on Docker Hub
    command: docker push isakggong/board-server:maryfarm-1.0
    tags: push_image
  - name: push the calendar image on Docker Hub
    command: docker push isakggong/calendar-server:maryfarm-1.0
    tags: push_image
    
  # remove images
  - name: remove the config image from the ansible server
    command: docker rmi isakggong/config-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the discovery image from the ansible server
    command: docker rmi isakggong/discovery-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the apigateway image from the ansible server
    command: docker rmi isakggong/apigateway-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the notify image from the ansible server
    command: docker rmi isakggong/notify-server:maryfarm-1.0   
    ignore_errors: yes
    tags: remove_image
  - name: remove the user image from the ansible server
    command: docker rmi isakggong/user-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the plant image from the ansible server
    command: docker rmi isakggong/plant-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the chat image from the ansible server
    command: docker rmi isakggong/chat-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the board image from the ansible server
    command: docker rmi isakggong/board-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  - name: remove the calendar image from the ansible server
    command: docker rmi isakggong/calendar-server:maryfarm-1.0
    ignore_errors: yes
    tags: remove_image
  
  - name: remove anonymous docker image
    # command: docker rmi $(docker images -f "dangling=true" -q)
    command: docker rmi $(docker images | grep "^<none>" | awk "{print $3}")
    ignore_errors: yes
    tags: remove_image
